"""
Simple SysML v2 parser to extract architecture information.

Parses the subset of SysML v2 textual syntax generated by json_to_sysml.py
and converts it back to JSON IR format for compatibility with existing tools.
"""
import re
from typing import Dict, List, Optional


def parse_sysml_to_json(sysml_content: str) -> Dict:
    """Parse SysML v2 textual content to JSON IR format"""

    lines = sysml_content.split('\n')

    # Extract package name and metadata
    package_name = extract_package_name(lines)
    domain = extract_domain_comment(lines)
    name = extract_name_comment(lines)

    # Parse definitions
    blocks = extract_part_definitions(sysml_content)
    proxy_ports = extract_ports_from_parts(sysml_content)
    requirements = extract_requirements(sysml_content)

    # Build instance-to-type mapping for proper name resolution
    instance_map = extract_part_instances(sysml_content)

    connectors = extract_connections(sysml_content, instance_map)
    relationships = extract_satisfy_relationships(sysml_content, instance_map)

    return {
        'id': package_name or 'unknown',
        'name': name or 'Unknown Architecture',
        'domain': domain or 'system',
        'format': 'sysml_v2_textual',
        'blocks': blocks,
        'proxy_ports': proxy_ports,
        'connectors': connectors,
        'requirements': requirements,
        'relationships': relationships
    }


def extract_package_name(lines: List[str]) -> Optional[str]:
    """Extract package name from first few lines"""
    for line in lines[:10]:
        match = re.match(r'\s*package\s+(\w+)', line)
        if match:
            return match.group(1)
    return None


def extract_domain_comment(lines: List[str]) -> Optional[str]:
    """Extract domain from comment line"""
    for line in lines[:20]:
        match = re.search(r'//\s*Domain:\s*(.+)', line)
        if match:
            return match.group(1).strip()
    return None


def extract_name_comment(lines: List[str]) -> Optional[str]:
    """Extract name from comment line"""
    for line in lines[:20]:
        # Look for "// Architecture Name" style comment
        if '//' in line and 'Domain:' not in line and 'package' not in line.lower():
            match = re.search(r'//\s*(.+)', line)
            if match:
                name = match.group(1).strip()
                if name and not name.startswith('Interface') and not name.startswith('Part'):
                    return name
    return None


def extract_part_definitions(content: str) -> List[Dict]:
    """Extract part definitions"""
    blocks = []

    # Match: part def BlockName {
    pattern = r'part\s+def\s+(\w+)\s*\{'
    matches = re.finditer(pattern, content)

    for match in matches:
        block_name = match.group(1)
        blocks.append({
            'name': block_name,
            'stereotype': 'Block'
        })

    return blocks


def extract_ports_from_parts(content: str) -> List[Dict]:
    """Extract ports from part definitions"""
    ports = []

    # Find each part def block with balanced braces
    part_pattern = r'part\s+def\s+(\w+)\s*\{'

    for part_match in re.finditer(part_pattern, content):
        owner = part_match.group(1)
        start_pos = part_match.end()

        # Find matching closing brace
        brace_count = 1
        pos = start_pos
        while pos < len(content) and brace_count > 0:
            if content[pos] == '{':
                brace_count += 1
            elif content[pos] == '}':
                brace_count -= 1
            pos += 1

        if brace_count == 0:
            part_body = content[start_pos:pos-1]

            # Find ports in this part
            port_pattern = r'port\s+(\w+)\s*:\s*(\w+)'
            for port_match in re.finditer(port_pattern, part_body):
                port_name = port_match.group(1)
                port_type = port_match.group(2)
                ports.append({
                    'owner': owner,
                    'name': port_name,
                    'type': port_type
                })

    return ports


def extract_requirements(content: str) -> List[Dict]:
    """Extract requirement definitions"""
    requirements = []

    # Match: requirement <'REQ-001'> {
    #          doc /* text */
    #        }
    pattern = r"requirement\s+<'([^']+)'>\s*\{[^}]*doc\s*/\*\s*([^*]+)\*/"

    for match in re.finditer(pattern, content, re.DOTALL):
        req_id = match.group(1)
        req_text = match.group(2).strip()
        requirements.append({
            'id': req_id,
            'text': req_text
        })

    return requirements


def extract_part_instances(content: str) -> Dict[str, str]:
    """Extract part instance to type mapping

    Parses: part instanceName : TypeName;
    Returns: {'instancename': 'TypeName'}
    """
    instance_map = {}

    # Match part instances: part instanceName : TypeName;
    pattern = r'part\s+(\w+)\s*:\s*(\w+)\s*[;{]'

    for match in re.finditer(pattern, content):
        instance_name = match.group(1).lower()
        type_name = match.group(2)
        instance_map[instance_name] = type_name

    return instance_map


def extract_connections(content: str, instance_map: Dict[str, str]) -> List[Dict]:
    """Extract connection definitions"""
    connectors = []

    # Match: connection : linkName connect
    #          partA.portA to partB.portB;
    # Allow whitespace including newlines between elements
    pattern = r'connection\s*:\s*(\w+)\s+connect\s+(\w+)\.(\w+)\s+to\s+(\w+)\.(\w+)'

    for match in re.finditer(pattern, content, re.DOTALL):
        conn_name = match.group(1)
        part_a = match.group(2).lower()
        port_a = match.group(3)
        part_b = match.group(4).lower()
        port_b = match.group(5)

        # Resolve instance names to type names
        type_a = instance_map.get(part_a, capitalize_part_name(part_a))
        type_b = instance_map.get(part_b, capitalize_part_name(part_b))

        connectors.append({
            'name': conn_name,
            'end_a': f'{type_a}.{port_a}',
            'end_b': f'{type_b}.{port_b}',
            'item_flow': ''  # Not captured in simple syntax
        })

    return connectors


def extract_satisfy_relationships(content: str, instance_map: Dict[str, str]) -> List[Dict]:
    """Extract satisfy relationships"""
    relationships = []

    # Match: satisfy requirement <'REQ-001'> by partName;
    pattern = r"satisfy\s+requirement\s+<'([^']+)'>\s+by\s+(\w+)"

    for match in re.finditer(pattern, content):
        req_id = match.group(1)
        client = match.group(2).lower()

        # Resolve instance name to type name
        type_name = instance_map.get(client, capitalize_part_name(client))

        relationships.append({
            'type': 'satisfy',
            'client': type_name,
            'supplier': req_id
        })

    return relationships


def capitalize_part_name(name: str) -> str:
    """Convert lowercase part instance names back to PascalCase"""
    # Simple heuristic: capitalize first letter and after underscores
    parts = name.split('_')
    return ''.join(p.capitalize() for p in parts)
