"""
Simple SysML v2 parser to extract architecture information.

Parses the subset of SysML v2 textual syntax generated by json_to_sysml.py
and converts it back to JSON IR format for compatibility with existing tools.
"""
import re
from pathlib import Path
from typing import Dict, List, Optional, Set


def parse_import_statement(line: str) -> Optional[str]:
    """
    Extract import target from import statement.

    Args:
        line: Line containing import statement

    Returns:
        Path to imported file, or None if not a file-based import

    Examples:
        'import "model.sysml";' -> "model.sysml"
        'import "../model.sysml";' -> "../model.sysml"
        'import arch_000001::*;' -> None (namespace import, not file)
    """
    # Match file-based imports: import "path/to/file.sysml";
    match = re.match(r'\s*import\s+"([^"]+)"\s*;', line)
    if match:
        return match.group(1)
    return None


def resolve_import_path(view_file: Path, import_target: str) -> Path:
    """
    Resolve relative import path from view file location.

    Args:
        view_file: Path to the view file containing import
        import_target: Target from import statement (e.g., "model.sysml", "../model.sysml")

    Returns:
        Absolute path to imported file

    Examples:
        view_file: /data/arch_000001/views/bdd.sysml
        import_target: "model.sysml"
        returns: /data/arch_000001/model.sysml

        view_file: /data/arch_000001/views/bdd.sysml
        import_target: "../model.sysml"
        returns: /data/arch_000001/model.sysml
    """
    # Get directory containing the view file
    view_dir = view_file.parent

    # If import_target is just a filename (no path separators), look in parent directory
    if '/' not in import_target and '\\' not in import_target:
        # Assume model.sysml is in parent directory of views/
        resolved = view_dir.parent / import_target
    else:
        # Relative path import
        resolved = (view_dir / import_target).resolve()

    return resolved


def has_imports(content: str) -> bool:
    """Check if content contains file-based import statements"""
    return bool(re.search(r'import\s+"[^"]+"', content))


def load_with_imports(file_path: Path, loaded_files: Optional[Set[Path]] = None) -> Dict:
    """
    Load a SysML file and recursively resolve imports.

    Args:
        file_path: Path to SysML file (model or view)
        loaded_files: Set of already loaded files (for circular dependency detection)

    Returns:
        Merged architecture dictionary with all imported content

    Process:
        1. Check for circular dependencies
        2. Parse file content
        3. Extract import statements
        4. Recursively load imported files
        5. Merge dictionaries (imported content first, local content overrides)

    Raises:
        FileNotFoundError: If imported file does not exist
        ValueError: If circular import detected
    """
    if loaded_files is None:
        loaded_files = set()

    # Resolve absolute path
    file_path = file_path.resolve()

    # Check for circular imports
    if file_path in loaded_files:
        raise ValueError(f"Circular import detected: {file_path}")

    # Add to loaded set
    loaded_files.add(file_path)

    # Read file content
    if not file_path.exists():
        raise FileNotFoundError(f"Import file not found: {file_path}")

    content = file_path.read_text(encoding='utf-8')
    lines = content.split('\n')

    # Find and process imports first
    merged_data = None

    for line in lines:
        import_target = parse_import_statement(line)
        if import_target:
            # Resolve import path
            import_path = resolve_import_path(file_path, import_target)

            try:
                # Recursively load imported file
                imported_data = load_with_imports(import_path, loaded_files.copy())

                # Merge imported data
                if merged_data is None:
                    merged_data = imported_data
                else:
                    merged_data = merge_architectures(merged_data, imported_data)
            except FileNotFoundError as e:
                # Log warning but continue (allows for missing imports in development)
                print(f"Warning: {e}")
            except ValueError as e:
                # Circular import - raise error
                raise e

    # Parse local content (without recursing on imports)
    local_data = parse_sysml_to_json(content, file_path=None)

    # Merge local data with imported data (local overrides)
    if merged_data:
        result = merge_architectures(merged_data, local_data)
    else:
        result = local_data

    # Mark as loaded from separated format if imports were found
    if merged_data:
        result['source'] = 'view'

    return result


def merge_architectures(base: Dict, override: Dict) -> Dict:
    """
    Merge two architecture dictionaries, with override taking precedence.

    Args:
        base: Base architecture dictionary (from imports)
        override: Override architecture dictionary (local content)

    Returns:
        Merged architecture dictionary
    """
    result = base.copy()

    # For view files, preserve the model's core identity
    # Only override if the override has meaningful content (not just view package name)
    is_view = 'view_metadata' in override or override.get('source') == 'view'

    if is_view:
        # View files should preserve model's id, name, domain
        # Only override format and source
        if 'format' in override and override['format']:
            result['format'] = override['format']
        if 'source' in override and override['source']:
            result['source'] = override['source']
    else:
        # Normal merge: override scalar fields
        for key in ['id', 'name', 'domain', 'format', 'source']:
            if key in override and override[key]:
                result[key] = override[key]

    # Merge list fields (deduplicate by relevant keys)
    for key in ['blocks', 'proxy_ports', 'connectors', 'requirements', 'relationships', 'compositions']:
        if key in override:
            if key not in result:
                result[key] = override[key]
            else:
                # Merge lists, avoiding duplicates
                result[key] = merge_list_field(result[key], override[key], key)

    # Add view metadata if present
    if 'view_metadata' in override:
        result['view_metadata'] = override['view_metadata']

    return result


def merge_list_field(base_list: List[Dict], override_list: List[Dict], field_name: str) -> List[Dict]:
    """
    Merge two lists of dictionaries, avoiding duplicates.

    Args:
        base_list: Base list (from imports)
        override_list: Override list (local content)
        field_name: Name of the field being merged (for determining key)

    Returns:
        Merged list with duplicates removed
    """
    # Define keys for deduplication
    keys = {
        'blocks': lambda x: x['name'],
        'proxy_ports': lambda x: (x['owner'], x['name']),
        'connectors': lambda x: x['name'],
        'requirements': lambda x: x['id'],
        'relationships': lambda x: (x['type'], x['client'], x['supplier']),
        'compositions': lambda x: (x['parent'], x['child'])
    }

    if field_name not in keys:
        # No deduplication strategy, just append
        return base_list + override_list

    key_func = keys[field_name]

    # Build set of existing keys
    existing = {key_func(item) for item in base_list}

    # Add items from override that aren't duplicates
    result = base_list.copy()
    for item in override_list:
        if key_func(item) not in existing:
            result.append(item)

    return result


def extract_view_metadata(content: str) -> Dict:
    """
    Extract view-specific metadata from comment blocks.

    Args:
        content: SysML file content

    Returns:
        Dictionary with view configuration

    Example output:
        {
            'viewType': 'BlockDefinitionDiagram',
            'showAttributes': True,
            'showPorts': False,
            'context': 'arch_000001::UavPayloadSystem'
        }
    """
    metadata = {}

    # Look for comment blocks with @key: value patterns
    # Matches: /* @viewType: BlockDefinitionDiagram */
    # or multiline: /*
    #                @viewType: BlockDefinitionDiagram
    #                @showPorts: true
    #                */
    comment_pattern = r'/\*\s*(.*?)\s*\*/'

    for match in re.finditer(comment_pattern, content, re.DOTALL):
        comment_text = match.group(1)

        # Extract key-value pairs
        kv_pattern = r'@(\w+)\s*:\s*(.+)'
        for kv_match in re.finditer(kv_pattern, comment_text):
            key = kv_match.group(1)
            value = kv_match.group(2).strip()

            # Parse boolean values
            if value.lower() == 'true':
                value = True
            elif value.lower() == 'false':
                value = False

            metadata[key] = value

    return metadata


def parse_sysml_to_json(sysml_content: str, file_path: Optional[Path] = None) -> Dict:
    """Parse SysML v2 textual content to JSON IR format

    Args:
        sysml_content: SysML v2 textual content
        file_path: Optional path to the file (for resolving imports)

    Returns:
        Architecture dictionary with parsed content

    Raises:
        ValueError: If content is not valid SysML v2 (missing package declaration)
    """

    lines = sysml_content.split('\n')

    # Check for imports and merge if present
    if file_path and has_imports(sysml_content):
        return load_with_imports(file_path)

    # Extract package name and metadata
    package_name = extract_package_name(lines)

    # Validate that package declaration exists
    if not package_name:
        raise ValueError("Invalid SysML v2 syntax: missing package declaration. Expected 'package <name> { ... }'")

    domain = extract_domain_comment(lines)
    name = extract_name_comment(lines)

    # Parse definitions
    blocks = extract_part_definitions(sysml_content)
    proxy_ports = extract_ports_from_parts(sysml_content)
    requirements = extract_requirements(sysml_content)
    compositions = extract_compositions(sysml_content)

    # Build instance-to-type mapping for proper name resolution
    instance_map = extract_part_instances(sysml_content)

    connectors = extract_connections(sysml_content, instance_map)
    relationships = extract_satisfy_relationships(sysml_content, instance_map)

    # Extract view metadata if present
    view_metadata = extract_view_metadata(sysml_content)

    # Determine source type
    source_type = 'view' if view_metadata else 'monolithic'

    result = {
        'id': package_name,  # guaranteed to exist due to validation above
        'name': name or 'Unknown Architecture',
        'domain': domain or 'system',
        'format': 'sysml_v2_textual',
        'source': source_type,
        'blocks': blocks,
        'proxy_ports': proxy_ports,
        'connectors': connectors,
        'requirements': requirements,
        'relationships': relationships,
        'compositions': compositions
    }

    # Add view metadata if present
    if view_metadata:
        result['view_metadata'] = view_metadata

    return result


def extract_package_name(lines: List[str]) -> Optional[str]:
    """Extract package name from first few lines"""
    for line in lines[:10]:
        match = re.match(r'\s*package\s+(\w+)', line)
        if match:
            return match.group(1)
    return None


def extract_domain_comment(lines: List[str]) -> Optional[str]:
    """Extract domain from comment line"""
    for line in lines[:20]:
        match = re.search(r'//\s*Domain:\s*(.+)', line)
        if match:
            return match.group(1).strip()
    return None


def extract_name_comment(lines: List[str]) -> Optional[str]:
    """Extract name from comment line"""
    for line in lines[:20]:
        # Look for "// Architecture Name" style comment
        if '//' in line and 'Domain:' not in line and 'package' not in line.lower():
            match = re.search(r'//\s*(.+)', line)
            if match:
                name = match.group(1).strip()
                if name and not name.startswith('Interface') and not name.startswith('Part'):
                    return name
    return None


def extract_part_definitions(content: str) -> List[Dict]:
    """Extract part definitions"""
    blocks = []

    # Match: part def BlockName {
    pattern = r'part\s+def\s+(\w+)\s*\{'
    matches = re.finditer(pattern, content)

    for match in matches:
        block_name = match.group(1)
        blocks.append({
            'name': block_name,
            'stereotype': 'Block'
        })

    return blocks


def extract_compositions(content: str) -> List[Dict]:
    """Extract composition relationships (which parts contain which other parts)

    Finds: part instanceName : TypeName inside part def blocks
    Returns: [{'parent': 'SystemBlock', 'child': 'ComponentBlock', 'multiplicity': '1'}, ...]
    """
    compositions = []

    # Find each part def block
    part_def_pattern = r'part\s+def\s+(\w+)\s*\{'

    for part_match in re.finditer(part_def_pattern, content):
        parent_name = part_match.group(1)
        start_pos = part_match.end()

        # Find matching closing brace
        brace_count = 1
        pos = start_pos
        while pos < len(content) and brace_count > 0:
            if content[pos] == '{':
                brace_count += 1
            elif content[pos] == '}':
                brace_count -= 1
            pos += 1

        if brace_count == 0:
            part_body = content[start_pos:pos-1]

            # Find part usages: part instanceName : TypeName[multiplicity]
            # Pattern matches: part wheel : Wheel[4]; or part engine : Engine;
            part_usage_pattern = r'part\s+\w+\s*:\s*(\w+)(?:\[(\d+)\])?'

            for usage_match in re.finditer(part_usage_pattern, part_body):
                child_type = usage_match.group(1)
                multiplicity = usage_match.group(2) if usage_match.group(2) else '1'
                compositions.append({
                    'parent': parent_name,
                    'child': child_type,
                    'multiplicity': multiplicity
                })

    return compositions


def extract_ports_from_parts(content: str) -> List[Dict]:
    """Extract ports from part definitions"""
    ports = []

    # Find each part def block with balanced braces
    part_pattern = r'part\s+def\s+(\w+)\s*\{'

    for part_match in re.finditer(part_pattern, content):
        owner = part_match.group(1)
        start_pos = part_match.end()

        # Find matching closing brace
        brace_count = 1
        pos = start_pos
        while pos < len(content) and brace_count > 0:
            if content[pos] == '{':
                brace_count += 1
            elif content[pos] == '}':
                brace_count -= 1
            pos += 1

        if brace_count == 0:
            part_body = content[start_pos:pos-1]

            # Find ports in this part
            # Match both: port name : Type; and port name;
            port_pattern_typed = r'port\s+(\w+)\s*:\s*(\w+)'
            port_pattern_untyped = r'port\s+(\w+)\s*;'

            # First find typed ports
            for port_match in re.finditer(port_pattern_typed, part_body):
                port_name = port_match.group(1)
                port_type = port_match.group(2)
                ports.append({
                    'owner': owner,
                    'name': port_name,
                    'type': port_type
                })

            # Then find untyped ports (those not already found)
            existing_ports = {p['name'] for p in ports if p['owner'] == owner}
            for port_match in re.finditer(port_pattern_untyped, part_body):
                port_name = port_match.group(1)
                if port_name not in existing_ports:
                    ports.append({
                        'owner': owner,
                        'name': port_name,
                        'type': 'Port'  # Default type
                    })

    return ports


def extract_requirements(content: str) -> List[Dict]:
    """Extract requirement definitions"""
    requirements = []

    # Match: requirement REQ_001 {
    #          doc "text"
    #        }
    pattern = r'requirement\s+(\w+)\s*\{\s*doc\s+"([^"]+)"'

    for match in re.finditer(pattern, content, re.DOTALL):
        req_id = match.group(1)
        req_text = match.group(2).strip()
        requirements.append({
            'id': req_id,
            'text': req_text
        })

    return requirements


def extract_part_instances(content: str) -> Dict[str, str]:
    """Extract part instance to type mapping

    Parses: part instanceName : TypeName[multiplicity];
    Returns: {'instancename': 'TypeName'}
    """
    instance_map = {}

    # Match part instances: part instanceName : TypeName; or part instanceName : TypeName[mult];
    # Pattern allows optional multiplicity like [1], [1..1], [4], etc.
    pattern = r'part\s+(\w+)\s*:\s*(\w+)(?:\[[^\]]*\])?\s*[;{]'

    for match in re.finditer(pattern, content):
        instance_name = match.group(1).lower()
        type_name = match.group(2)
        instance_map[instance_name] = type_name

    return instance_map


def extract_connections(content: str, instance_map: Dict[str, str]) -> List[Dict]:
    """Extract connection definitions"""
    connectors = []
    conn_counter = 1

    # Match pattern 1: connection : linkName connect partA.portA to partB.portB;
    pattern1 = r'connection\s*:\s*(\w+)\s+connect\s+(\w+)\.(\w+)\s+to\s+(\w+)\.(\w+)'

    for match in re.finditer(pattern1, content, re.DOTALL):
        conn_name = match.group(1)
        part_a = match.group(2).lower()
        port_a = match.group(3)
        part_b = match.group(4).lower()
        port_b = match.group(5)

        # Resolve instance names to type names
        type_a = instance_map.get(part_a, capitalize_part_name(part_a))
        type_b = instance_map.get(part_b, capitalize_part_name(part_b))

        connectors.append({
            'name': conn_name,
            'end_a': f'{type_a}.{port_a}',
            'end_b': f'{type_b}.{port_b}',
            'item_flow': ''
        })

    # Match pattern 2: connect SOURCE to TARGET;
    # This handles four cases:
    #   - part.port to part.port (port-to-port connection)
    #   - part.port to port (connection to boundary port)
    #   - port to part.port (connection from boundary port)
    #   - part to part (part-to-part connection without ports)
    pattern2 = r'connect\s+((?:\w+\.)?(?:\w+))\s+to\s+((?:\w+\.)?(?:\w+))\s*;'

    for match in re.finditer(pattern2, content):
        source = match.group(1)
        target = match.group(2)

        # Parse source
        if '.' in source:
            source_parts = source.split('.')
            part_a = source_parts[0].lower()
            port_a = source_parts[1]
            type_a = instance_map.get(part_a, capitalize_part_name(part_a))
            end_a = f'{type_a}.{port_a}'
        else:
            # Could be boundary port or part-to-part connection
            # Check if it's in instance_map (then it's a part)
            part_lower = source.lower()
            if part_lower in instance_map:
                # Part-to-part connection
                type_a = instance_map.get(part_lower, capitalize_part_name(part_lower))
                end_a = type_a
            else:
                # Boundary port
                end_a = source

        # Parse target
        if '.' in target:
            target_parts = target.split('.')
            part_b = target_parts[0].lower()
            port_b = target_parts[1]
            type_b = instance_map.get(part_b, capitalize_part_name(part_b))
            end_b = f'{type_b}.{port_b}'
        else:
            # Could be boundary port or part-to-part connection
            # Check if it's in instance_map (then it's a part)
            part_lower = target.lower()
            if part_lower in instance_map:
                # Part-to-part connection
                type_b = instance_map.get(part_lower, capitalize_part_name(part_lower))
                end_b = type_b
            else:
                # Boundary port
                end_b = target

        connectors.append({
            'name': f'conn_{conn_counter:03d}',
            'end_a': end_a,
            'end_b': end_b,
            'item_flow': ''
        })
        conn_counter += 1

    return connectors


def extract_satisfy_relationships(content: str, instance_map: Dict[str, str]) -> List[Dict]:
    """Extract satisfy relationships"""
    relationships = []

    # Match: satisfy REQ_001;
    # These appear inside part definitions, so we need to find which part they're in
    pattern = r'satisfy\s+(\w+)\s*;'

    # Find all part definitions to map satisfy statements to their owners
    part_pattern = r'part\s+(\w+)\s*:\s*(\w+)\s*\{'

    for part_match in re.finditer(part_pattern, content):
        instance_name = part_match.group(1).lower()
        type_name = part_match.group(2)
        start_pos = part_match.end()

        # Find matching closing brace
        brace_count = 1
        pos = start_pos
        while pos < len(content) and brace_count > 0:
            if content[pos] == '{':
                brace_count += 1
            elif content[pos] == '}':
                brace_count -= 1
            pos += 1

        if brace_count == 0:
            part_body = content[start_pos:pos-1]

            # Find satisfy statements in this part
            for satisfy_match in re.finditer(pattern, part_body):
                req_id = satisfy_match.group(1)
                relationships.append({
                    'type': 'satisfy',
                    'client': type_name,
                    'supplier': req_id
                })

    return relationships


def capitalize_part_name(name: str) -> str:
    """Convert lowercase part instance names back to PascalCase"""
    # Simple heuristic: capitalize first letter and after underscores
    parts = name.split('_')
    return ''.join(p.capitalize() for p in parts)
